import React from 'react';
import revistaDb from '../../data/lions-revista-db';
import PrintButton from '../../PrintButton';

const fmt = new Intl.NumberFormat('pt-BR');
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',maximumFractionDigits:0});
const g = revistaDb.global;
const issue = revistaDb.monthlyMagazine.issues[0];

const css = `
  .printBar{position:sticky;top:0;z-index:20;background:#fff;border-bottom:1px solid #d9e2ef;padding:12px 0}.printBar .inner{width:min(980px,92vw);margin:auto;display:flex;gap:10px;justify-content:space-between;align-items:center}.printBtn{border:0;border-radius:999px;background:#ffcc00;color:#172033;font-weight:900;padding:12px 18px;cursor:pointer}.backBtn{color:#00338d;font-weight:900;text-decoration:none}.magazine{width:min(980px,92vw);margin:28px auto 80px;font-family:Inter,system-ui,Segoe UI,Arial,sans-serif;color:#172033}.cover{min-height:720px;border-radius:36px;padding:52px;background:radial-gradient(circle at 78% 20%,#ffcc0066,transparent 28%),linear-gradient(135deg,#061b45,#00338d);color:white;display:grid;align-content:space-between;box-shadow:0 24px 70px #00195033}.seal{display:inline-flex;gap:10px;align-items:center;width:max-content;border:1px solid #ffffff44;background:#ffffff1e;border-radius:999px;padding:8px 13px;font-weight:900}.cover h1{font-size:clamp(3rem,8vw,6.6rem);line-height:.88;letter-spacing:-.08em;margin:28px 0}.cover p{font-size:1.25rem;color:#dbe7ff;max-width:720px}.coverMeta{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.coverMeta div,.stat{background:#ffffff14;border:1px solid #ffffff26;border-radius:20px;padding:18px}.coverMeta b,.stat b{display:block;font-size:1.5rem;color:#ffcc00}.page{page-break-before:always;margin-top:34px;background:white;border:1px solid #d9e2ef;border-radius:28px;padding:34px;box-shadow:0 18px 45px #00195014}.page h2{color:#00338d;font-size:2rem;margin:0 0 14px;letter-spacing:-.04em}.lead{font-size:1.08rem;color:#65758b}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:18px}.stat{background:#f8fbff;color:#172033}.stat b{color:#00338d}.causes{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:18px}.cause{border:1px solid #d9e2ef;border-radius:18px;padding:16px;background:#fff}.cause strong{display:block;color:#00338d}.sectionGrid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.sourceList{font-size:.92rem;color:#65758b}.sourceList a{color:#00338d}.callout{background:#fff8d6;border:1px solid #fde68a;border-radius:20px;padding:18px;margin-top:16px}.agenda li{margin:8px 0}@media(max-width:760px){.cover{min-height:580px;padding:30px}.coverMeta,.stats,.causes,.sectionGrid{grid-template-columns:1fr}.page{padding:24px}}@media print{.printBar{display:none}.magazine{width:100%;margin:0}.cover,.page{box-shadow:none;border-radius:0;border:0;min-height:auto}.page{break-before:page}.cover{break-after:page}body{background:white}.sourceList a{color:#172033;text-decoration:none}}
`;

export const metadata = { title: issue.title + ' | Lions Clube Juazeiro do Norte' };

function Stat({label,value,sub}){return React.createElement('div',{className:'stat'},React.createElement('b',null,value),React.createElement('span',null,label),sub?React.createElement('p',null,sub):null)}

export default function IssuePage(){
  return React.createElement(React.Fragment,null,
    React.createElement('style',{dangerouslySetInnerHTML:{__html:css}}),
    React.createElement('div',{className:'printBar'},React.createElement('div',{className:'inner'},React.createElement('a',{className:'backBtn',href:'/revista'},'← Revista mensal'),React.createElement(PrintButton))),
    React.createElement('main',{className:'magazine'},
      React.createElement('section',{className:'cover'},
        React.createElement('div',null,React.createElement('span',{className:'seal'},'● '+revistaDb.localClub.name),React.createElement('h1',null,'Revista AL nº 1'),React.createElement('p',null,issue.coverLine+'. Uma edição modelo para transformar dados reais, campanhas e ações locais em memória viva do serviço leonístico.')),
        React.createElement('div',{className:'coverMeta'},React.createElement('div',null,React.createElement('b',null,issue.month),React.createElement('span',null,revistaDb.dla4.cycle)),React.createElement('div',null,React.createElement('b',null,revistaDb.dla4.name),React.createElement('span',null,revistaDb.dmla.region)),React.createElement('div',null,React.createElement('b',null,'PDF'),React.createElement('span',null,'exibição web e impressão')))
      ),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Editorial'),React.createElement('p',{className:'lead'},'Esta edição funda a revista virtual mensal do Lions Clube Juazeiro do Norte. O formato segue a lógica editorial de uma revista: capa, editorial, matérias temáticas, números de impacto, agenda, fontes e versão para PDF.'),React.createElement('div',{className:'callout'},React.createElement('b',null,'Regra editorial: '),'dados globais e distritais entram com fonte; atividades locais entram com validação da diretoria, fotos, data, local e número de pessoas atendidas.')),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Impacto global Lions'),React.createElement('p',{className:'lead'},'Dados oficiais reunidos para alimentar mensalmente a revista com contexto mundial de serviço.'),React.createElement('div',{className:'stats'},React.createElement(Stat,{label:'pessoas servidas',value:fmt.format(g.impact.peopleServed),sub:g.impactPeriod}),React.createElement(Stat,{label:'projetos de serviço',value:fmt.format(g.impact.projectsCompleted)}),React.createElement(Stat,{label:'subsídios LCIF desde 1968',value:fmt.format(g.impact.lcifGrantsSince1968)}),React.createElement(Stat,{label:'subsídios LCIF 2024/2025',value:fmt.format(g.impact.lcifGrantsAwarded2024_2025)}),React.createElement(Stat,{label:'valor em subsídios 2024/2025',value:money.format(g.impact.lcifGrantTotalUSD2024_2025)}),React.createElement(Stat,{label:'captado pela LCIF 2024/2025',value:money.format(g.impact.lcifFundsRaisedUSD2024_2025)}))),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'LCIF: a Fundação que amplia o servir'),React.createElement('p',{className:'lead'},revistaDb.lcif.mission),React.createElement('div',{className:'stats'},React.createElement(Stat,{label:'fundação',value:String(revistaDb.lcif.foundedAt)}),React.createElement(Stat,{label:'socorro em catástrofes',value:money.format(revistaDb.lcif.impact.disasterReliefSupportUSD)}),React.createElement(Stat,{label:'Lions Quest estudantes',value:fmt.format(revistaDb.lcif.impact.lionsQuestStudents)}),React.createElement(Stat,{label:'SightFirst vidas impactadas',value:fmt.format(revistaDb.lcif.impact.sightFirst.impactedLives)}),React.createElement(Stat,{label:'SightFirst projetos',value:fmt.format(revistaDb.lcif.impact.sightFirst.projects)}),React.createElement(Stat,{label:'cirurgias de catarata',value:fmt.format(revistaDb.lcif.impact.sightFirst.cataractSurgeries)}))),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Causas globais e campanhas relevantes'),React.createElement('p',{className:'lead'},'Cada campanha local poderá ser vinculada a uma causa global para facilitar relatórios e narrativa editorial.'),React.createElement('div',{className:'causes'},g.causes.map(c=>React.createElement('div',{className:'cause',key:c.name},React.createElement('strong',null,c.name),React.createElement('span',null,fmt.format(c.peopleServed)+' pessoas servidas no recorte global disponível'))))),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Brasil, DMLA e Distrito LA-4'),React.createElement('div',{className:'sectionGrid'},React.createElement('article',null,React.createElement('h3',null,'Lions no Brasil'),React.createElement('p',null,'A base editorial registra os Distritos Múltiplos LA, LB, LC e LD para contextualizar matérias nacionais.')),React.createElement('article',null,React.createElement('h3',null,revistaDb.dmla.name),React.createElement('p',null,revistaDb.dmla.region),React.createElement('p',null,revistaDb.dmla.districts.join(' · '))),React.createElement('article',null,React.createElement('h3',null,revistaDb.dla4.name),React.createElement('p',null,revistaDb.dla4.state+' · '+revistaDb.dla4.cycle),React.createElement('p',null,revistaDb.dla4.mottoFromLogo)),React.createElement('article',null,React.createElement('h3',null,'Uso mensal'),React.createElement('p',null,revistaDb.dla4.editorialUse))))),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Lions Clube Juazeiro do Norte'),React.createElement('p',{className:'lead'},'A seção local deve registrar o que foi realizado no mês: campanha, data, local, fotos, parceiros, voluntários, pessoas atendidas e próximos passos.'),React.createElement('div',{className:'stats'},React.createElement(Stat,{label:'Distrito',value:revistaDb.localClub.district}),React.createElement(Stat,{label:'Divisão',value:revistaDb.localClub.division}),React.createElement(Stat,{label:'Região',value:'Cariri'})),React.createElement('div',{className:'callout'},'Campos mensais: título, data, causa global, local, responsável, parceiros, pessoas atendidas, voluntários, resumo, fotos, fontes e status de validação.')),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Agenda da próxima edição'),React.createElement('ul',{className:'agenda'},React.createElement('li',null,'Inserir atividades locais validadas pela diretoria.'),React.createElement('li',null,'Coletar notícias e campanhas do Distrito LA-4.'),React.createElement('li',null,'Atualizar dados oficiais Lions International/LCIF.'),React.createElement('li',null,'Gerar PDF histórico da edição mensal.'))),
      React.createElement('section',{className:'page'},React.createElement('h2',null,'Fontes'),React.createElement('ol',{className:'sourceList'},revistaDb.sources.map(s=>React.createElement('li',{key:s.id},React.createElement('a',{href:s.url,target:'_blank'},s.title),' — ',s.scope))))
    )
  );
}
