import React from 'react';

const script = `
(function(){
  let campaigns=[];
  const esc=(v)=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const toast=(m,isError)=>{let t=document.getElementById('toast');if(t){t.textContent=m;t.style.background=isError?'#991b1b':'#061b45';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200);}};
  function fromDb(row){return [row.titulo||'',row.causa_global||'',row.data_inicio||'',row.local||'',row.resumo||'',Array.isArray(row.fotos)?row.fotos:[],row.id||''];}
  function toDb(values){return {titulo:values[0]||'',causa_global:values[1]||'',data_inicio:values[2]||'',local:values[3]||'',resumo:values[4]||'',fotos:Array.isArray(values[5])?values[5]:[],id:values[6]||undefined,status:'publicada'};}
  function photoUrls(c){return Array.isArray(c[5])?c[5].filter(Boolean):[];}
  function ensureStyles(){if(document.getElementById('campaigns-db-styles'))return;const s=document.createElement('style');s.id='campaigns-db-styles';s.textContent='.campaignWithPhotos{overflow:hidden}.campaignSlider{display:flex;gap:10px;overflow-x:auto;scroll-snap-type:x mandatory;margin:-24px -24px 18px;padding:0 0 8px}.campaignSlider img{min-width:100%;height:220px;object-fit:cover;scroll-snap-align:start;background:#eef3f9}.campaignPhotoPlaceholder{height:180px;margin:-24px -24px 18px;background:linear-gradient(135deg,#dbeafe,#fff8d6);display:grid;place-items:center;color:#64748b;font-weight:900}.latestCampaignsHome{width:min(1180px,92vw);margin:34px auto 0}.latestCampaignsHome h2{font-size:clamp(1.8rem,3vw,2.6rem);letter-spacing:-.05em;margin-bottom:10px}.latestCampaignsGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.latestCampaignsGrid .campaign .btn{margin-top:12px}.dbBadge{display:inline-flex;margin-left:8px;padding:4px 8px;border-radius:999px;background:#eef5ff;color:#00338d;font-size:.75rem;font-weight:900}.uploadStatus{display:block;color:#65758b;font-size:.8rem;margin-top:6px}.photoList{display:grid;gap:5px;margin-top:6px}.photoList small{word-break:break-all;color:#65758b}@media(max-width:760px){.latestCampaignsGrid{grid-template-columns:1fr}.campaignSlider img{height:200px}.adminEditableTable{display:block;overflow-x:auto}.adminEditableTable table,.adminEditableTable tbody,.adminEditableTable tr,.adminEditableTable td{display:block}.adminEditableTable td{margin-bottom:8px}}';document.head.appendChild(s);}
  function photosHtml(c){const p=photoUrls(c);if(!p.length)return '<div class="campaignPhotoPlaceholder">Foto da campanha</div>';return '<div class="campaignSlider">'+p.map((url,i)=>'<img src="'+esc(url)+'" alt="Foto da campanha '+(i+1)+'" loading="lazy">').join('')+'</div>';}
  function card(c,compact){return '<article class="campaign campaignWithPhotos">'+photosHtml(c)+'<span class="tag">'+esc(c[1])+'</span><h2>'+esc(c[0])+'</h2><p><b>'+esc(c[2])+'</b> · '+esc(c[3])+'</p><p>'+esc(c[4])+'</p>'+(compact?'<a class="btn" href="/campanhas">Ver campanha</a>':'')+'</article>';}
  function placeLatest(holder){const cause=document.querySelector('.causeRow');const causeCard=cause?cause.closest('.intelCard'):null;if(causeCard){causeCard.after(holder);return;}const intel=document.querySelector('.intelHome');if(intel){intel.appendChild(holder);return;}const hero=document.querySelector('.hero');if(hero)hero.after(holder);}
  function placeFooter(holder){const foot=document.querySelector('.foot');if(!foot)return;const useful=document.querySelector('.usefulLinks');const usefulCard=useful?useful.closest('.intelCard'):null;if(usefulCard){usefulCard.after(foot);return;}if(holder)holder.after(foot);}
  function renderPublic(){ensureStyles();const grid=document.getElementById('campaignGrid');if(grid)grid.innerHTML=campaigns.map(c=>card(c,false)).join('');if(location.pathname==='/'||location.pathname===''){let holder=document.getElementById('latestCampaignsHome');const list=campaigns.slice(0,2);if(!list.length){if(holder)holder.remove();placeFooter(null);return;}if(!holder){holder=document.createElement('section');holder.id='latestCampaignsHome';holder.className='latestCampaignsHome';}holder.innerHTML='<h2>Últimas campanhas</h2><div class="latestCampaignsGrid">'+list.map(c=>card(c,true)).join('')+'</div>';placeLatest(holder);placeFooter(holder);}}
  async function loadDb(){const r=await fetch('/api/campanhas',{cache:'no-store'});const j=await r.json();if(!r.ok||!j||!j.ok||j.configured===false||!Array.isArray(j.data))throw new Error(j&&j.error?j.error:'Não foi possível carregar as campanhas do banco.');campaigns=j.data.map(fromDb);renderPublic();return campaigns;}
  async function uploadFiles(files,statusEl){if(!files||!files.length)return [];const fd=new FormData();Array.from(files).forEach(file=>fd.append('files',file));if(statusEl)statusEl.textContent='Enviando '+files.length+' foto(s) ao ImgBB...';const r=await fetch('/api/imgbb',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j||!j.ok)throw new Error(j&&j.error?j.error:'Falha no upload para o ImgBB.');if(statusEl)statusEl.textContent=j.data.length+' foto(s) armazenada(s) no ImgBB.';return j.data.map(x=>x.url);}
  async function saveCampaign(values){const r=await fetch('/api/campanhas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(toDb(values))});const j=await r.json();if(!r.ok||!j||!j.ok)throw new Error(j&&j.error?j.error:'Não foi possível salvar a campanha no banco.');await loadDb();toast(values[6]?'Alteração salva no banco':'Campanha salva no banco');return true;}
  async function deleteCampaign(values){if(!values[6])throw new Error('Campanha sem ID de banco.');const r=await fetch('/api/campanhas?id='+encodeURIComponent(values[6]),{method:'DELETE'});const j=await r.json();if(!r.ok||!j||!j.ok)throw new Error(j&&j.error?j.error:'Não foi possível excluir a campanha.');await loadDb();toast('Campanha excluída do banco');}
  function photoSummary(urls){if(!urls.length)return 'Nenhuma foto';return urls.length+' foto(s) no ImgBB';}
  function rowHtml(r,i,editing){const labels=['Título','Causa','Data','Local','Resumo'];if(editing){return '<tr data-row="'+i+'">'+labels.map((l,idx)=>'<td><label style="display:block;font-weight:800;color:#00338d;font-size:.78rem">'+l+'<input data-field="'+idx+'" value="'+esc(r[idx])+'" style="width:100%;min-width:140px;border:1px solid #d9e2ef;border-radius:10px;padding:9px;margin-top:4px;font:inherit"></label></td>').join('')+'<td><label style="display:block;font-weight:800;color:#00338d;font-size:.78rem">Adicionar fotos<input data-new-files type="file" accept="image/*" multiple style="width:100%;margin-top:6px"></label><small class="uploadStatus">Fotos atuais: '+esc(photoSummary(photoUrls(r)))+'</small></td><td style="white-space:nowrap"><button data-save="'+i+'">Salvar</button> <button data-cancel="'+i+'">Cancelar</button></td></tr>';}return '<tr data-row="'+i+'"><td>'+esc(r[0])+'</td><td>'+esc(r[1])+'</td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+esc(r[4])+'</td><td>'+esc(photoSummary(photoUrls(r)))+'</td><td style="white-space:nowrap"><button data-edit="'+i+'">Editar</button> <button data-del="'+i+'">Excluir</button></td></tr>';}
  function bindRows(){const m=document.getElementById('adminMain');if(!m)return;m.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const i=+b.dataset.edit;const tr=m.querySelector('tr[data-row="'+i+'"]');if(tr){tr.outerHTML=rowHtml(campaigns[i]||[],i,true);bindRows();}});m.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>renderCampaignAdmin());m.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{b.disabled=true;const i=+b.dataset.save;const tr=m.querySelector('tr[data-row="'+i+'"]');const inputs=Array.from(tr.querySelectorAll('input[data-field]'));const values=inputs.map(inp=>inp.value);const current=campaigns[i]||[];const status=tr.querySelector('.uploadStatus');try{const added=await uploadFiles(tr.querySelector('[data-new-files]').files,status);values[5]=photoUrls(current).concat(added);values[6]=current[6];await saveCampaign(values);renderCampaignAdmin();}catch(e){toast(e.message,true);b.disabled=false;}});m.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta campanha?'))return;b.disabled=true;try{await deleteCampaign(campaigns[+b.dataset.del]||[]);renderCampaignAdmin();}catch(e){toast(e.message,true);b.disabled=false;}});}
  function renderCampaignAdmin(){const m=document.getElementById('adminMain');if(!m)return;ensureStyles();m.innerHTML='<h2>Campanhas <span class="dbBadge">Supabase + ImgBB</span></h2><form id="campaignDbForm" class="form"><label>Título<input name="titulo" required></label><label>Causa<input name="causa" required></label><label>Data<input name="data" type="date" required></label><label>Local<input name="local" required></label><label>Resumo<input name="resumo" required></label><label>Fotos da campanha<input name="fotos" type="file" accept="image/*" multiple><small id="campaignUploadStatus" class="uploadStatus">As fotos serão enviadas ao ImgBB.</small></label><button>Adicionar campanha</button></form><table class="table adminEditableTable"><tbody>'+campaigns.map((r,i)=>rowHtml(r,i,false)).join('')+'</tbody></table>';
    document.getElementById('campaignDbForm').onsubmit=async(e)=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"],button');button.disabled=true;const f=new FormData(e.target);try{const urls=await uploadFiles(e.target.elements.fotos.files,document.getElementById('campaignUploadStatus'));const values=[f.get('titulo'),f.get('causa'),f.get('data'),f.get('local'),f.get('resumo'),urls,''];await saveCampaign(values);e.target.reset();renderCampaignAdmin();}catch(err){toast(err.message,true);button.disabled=false;}};bindRows();}
  const previousTab=window.tab;
  window.tab=function(t){if(t==='campaigns'){loadDb().then(renderCampaignAdmin).catch(e=>{toast(e.message,true);const m=document.getElementById('adminMain');if(m)m.innerHTML='<h2>Campanhas</h2><p>Não foi possível acessar o banco compartilhado.</p>';});return;}if(typeof previousTab==='function')return previousTab(t);};
  function boot(){loadDb().catch(e=>console.error(e));document.querySelectorAll('[data-tab="campaigns"]').forEach(b=>b.onclick=function(){window.tab('campaigns');});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;

export default function CampaignsDbPatch(){return React.createElement('script',{dangerouslySetInnerHTML:{__html:script}});}
