import React from 'react';

const script = `
(function(){
  const LS={campaigns:'lj_campaigns'};
  const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch(e){return d;}};
  const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=(v)=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const toast=(m)=>{let t=document.getElementById('toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}};

  function fromDb(row){return [row.titulo||'',row.causa_global||'',row.data_inicio||'',row.local||'',row.resumo||'',Array.isArray(row.fotos)?row.fotos.join(', '):(row.fotos||''),row.id||''];}
  function toDb(values){return {titulo:values[0]||'',causa_global:values[1]||'',data_inicio:values[2]||'',local:values[3]||'',resumo:values[4]||'',fotos:String(values[5]||'').split(',').map(x=>x.trim()).filter(Boolean),id:values[6]||undefined,status:'publicada'};}
  function photoUrls(c){return String(c[5]||'').split(',').map(x=>x.trim()).filter(Boolean);}
  function ensureStyles(){if(document.getElementById('campaigns-db-styles'))return;const s=document.createElement('style');s.id='campaigns-db-styles';s.textContent='.campaignWithPhotos{overflow:hidden}.campaignSlider{display:flex;gap:10px;overflow-x:auto;scroll-snap-type:x mandatory;margin:-24px -24px 18px;padding:0 0 8px}.campaignSlider img{min-width:100%;height:220px;object-fit:cover;scroll-snap-align:start;background:#eef3f9}.campaignPhotoPlaceholder{height:180px;margin:-24px -24px 18px;background:linear-gradient(135deg,#dbeafe,#fff8d6);display:grid;place-items:center;color:#64748b;font-weight:900}.latestCampaignsHome{width:min(1180px,92vw);margin:34px auto 0}.latestCampaignsHome h2{font-size:clamp(1.8rem,3vw,2.6rem);letter-spacing:-.05em;margin-bottom:10px}.latestCampaignsGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.latestCampaignsGrid .campaign .btn{margin-top:12px}.dbBadge{display:inline-flex;margin-left:8px;padding:4px 8px;border-radius:999px;background:#eef5ff;color:#00338d;font-size:.75rem;font-weight:900}@media(max-width:760px){.latestCampaignsGrid{grid-template-columns:1fr}.campaignSlider img{height:200px}.adminEditableTable{display:block;overflow-x:auto}.adminEditableTable table,.adminEditableTable tbody,.adminEditableTable tr,.adminEditableTable td{display:block}.adminEditableTable td{margin-bottom:8px}}';document.head.appendChild(s);}
  function photosHtml(c){const p=photoUrls(c);if(!p.length)return '<div class="campaignPhotoPlaceholder">Foto da campanha</div>';return '<div class="campaignSlider">'+p.map((url,i)=>'<img src="'+esc(url)+'" alt="Foto da campanha '+(i+1)+'" loading="lazy">').join('')+'</div>';}
  function card(c,compact){return '<article class="campaign campaignWithPhotos">'+photosHtml(c)+'<span class="tag">'+esc(c[1])+'</span><h2>'+esc(c[0])+'</h2><p><b>'+esc(c[2])+'</b> · '+esc(c[3])+'</p><p>'+esc(c[4])+'</p>'+(compact?'<a class="btn" href="/campanhas">Ver campanha</a>':'')+'</article>';}
  function placeLatest(holder){const cause=document.querySelector('.causeRow');const causeCard=cause?cause.closest('.intelCard'):null;if(causeCard){causeCard.after(holder);return;}const intel=document.querySelector('.intelHome');if(intel){intel.appendChild(holder);return;}const hero=document.querySelector('.hero');if(hero)hero.after(holder);}
  function renderPublic(){ensureStyles();const data=get(LS.campaigns,[]);const grid=document.getElementById('campaignGrid');if(grid)grid.innerHTML=data.map(c=>card(c,false)).join('');if(location.pathname==='/'||location.pathname===''){let holder=document.getElementById('latestCampaignsHome');const list=data.slice(0,2);if(!list.length)return;if(!holder){holder=document.createElement('section');holder.id='latestCampaignsHome';holder.className='latestCampaignsHome';}holder.innerHTML='<h2>Últimas campanhas</h2><div class="latestCampaignsGrid">'+list.map(c=>card(c,true)).join('')+'</div>';placeLatest(holder);const foot=document.querySelector('.foot');if(foot)holder.after(foot);}}

  async function loadDb(){try{const r=await fetch('/api/campanhas',{cache:'no-store'});const j=await r.json();if(j&&j.ok&&j.configured!==false&&Array.isArray(j.data)){set(LS.campaigns,j.data.map(fromDb));renderPublic();return true;}}catch(e){}renderPublic();return false;}
  async function saveCampaign(values){try{const r=await fetch('/api/campanhas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(toDb(values))});const j=await r.json();if(j&&j.ok){await loadDb();toast(values[6]?'Alteração salva no banco':'Campanha salva no banco');return true;}toast('Banco ainda não configurado; salvo localmente');}catch(e){toast('Banco indisponível; salvo localmente');}return false;}
  async function deleteCampaign(values,index){if(values[6]){try{const r=await fetch('/api/campanhas?id='+encodeURIComponent(values[6]),{method:'DELETE'});const j=await r.json();if(j&&j.ok){await loadDb();toast('Excluído do banco');return true;}}catch(e){}}
    const data=get(LS.campaigns,[]);data.splice(index,1);set(LS.campaigns,data);renderCampaignAdmin();renderPublic();toast('Excluído localmente');return false;}

  function rowHtml(r,i,editing){const labels=['Título','Causa','Data','Local','Resumo','Fotos da campanha'];if(editing){return '<tr data-row="'+i+'">'+labels.map((l,idx)=>'<td><label style="display:block;font-weight:800;color:#00338d;font-size:.78rem">'+l+'<input data-field="'+idx+'" value="'+esc(r[idx])+'" style="width:100%;min-width:140px;border:1px solid #d9e2ef;border-radius:10px;padding:9px;margin-top:4px;font:inherit"></label></td>').join('')+'<td style="white-space:nowrap"><button data-save="'+i+'">Salvar</button> <button data-cancel="'+i+'">Cancelar</button></td></tr>';}return '<tr data-row="'+i+'"><td>'+esc(r[0])+'</td><td>'+esc(r[1])+'</td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+esc(r[4])+'</td><td>'+esc(r[5])+'</td><td style="white-space:nowrap"><button data-edit="'+i+'">Editar</button> <button data-del="'+i+'">Excluir</button></td></tr>';}
  function bindRows(){const m=document.getElementById('adminMain');if(!m)return;m.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const data=get(LS.campaigns,[]);const i=+b.dataset.edit;const tr=m.querySelector('tr[data-row="'+i+'"]');if(tr){tr.outerHTML=rowHtml(data[i]||[],i,true);bindRows();}});m.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>renderCampaignAdmin());m.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const data=get(LS.campaigns,[]);const i=+b.dataset.save;const tr=m.querySelector('tr[data-row="'+i+'"]');const values=Array.from(tr.querySelectorAll('input[data-field]')).map(inp=>inp.value);values[6]=data[i]&&data[i][6];const ok=await saveCampaign(values);if(!ok){data[i]=values;set(LS.campaigns,data);renderPublic();}renderCampaignAdmin();});m.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const data=get(LS.campaigns,[]);const i=+b.dataset.del;await deleteCampaign(data[i]||[],i);});}
  function renderCampaignAdmin(){const m=document.getElementById('adminMain');if(!m)return;ensureStyles();const data=get(LS.campaigns,[]);m.innerHTML='<h2>Campanhas <span class="dbBadge">banco compartilhado</span></h2><form id="campaignDbForm" class="form"><label>Título<input name="titulo" required></label><label>Causa<input name="causa" required></label><label>Data<input name="data" required></label><label>Local<input name="local" required></label><label>Resumo<input name="resumo" required></label><label>Fotos da campanha<input name="fotos" placeholder="URLs separadas por vírgula"></label><button>Adicionar campanha</button></form><table class="table adminEditableTable"><tbody>'+data.map((r,i)=>rowHtml(r,i,false)).join('')+'</tbody></table>';
    document.getElementById('campaignDbForm').onsubmit=async(e)=>{e.preventDefault();const f=new FormData(e.target);const values=[f.get('titulo'),f.get('causa'),f.get('data'),f.get('local'),f.get('resumo'),f.get('fotos'),''];const ok=await saveCampaign(values);if(!ok){const data=get(LS.campaigns,[]);data.unshift(values);set(LS.campaigns,data);renderPublic();}e.target.reset();renderCampaignAdmin();};bindRows();}

  const previousTab=window.tab;
  window.tab=function(t){if(t==='campaigns'){loadDb().then(renderCampaignAdmin);return;}if(typeof previousTab==='function')return previousTab(t);};
  function boot(){loadDb();document.querySelectorAll('[data-tab="campaigns"]').forEach(b=>b.onclick=function(){window.tab('campaigns');});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,700);setTimeout(boot,1800);
})();
`;

export default function CampaignsDbPatch(){return React.createElement('script',{dangerouslySetInnerHTML:{__html:script}});}
