'use client';

import React from 'react';
import revistaDb from './data/lions-revista-db';

const fmt = new Intl.NumberFormat('pt-BR');
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',maximumFractionDigits:0});

const css = `
.intelHome{width:min(1180px,92vw);margin:0 auto;padding:54px 0 10px;font-family:Inter,system-ui,Segoe UI,Arial,sans-serif;color:#172033}.intelHeader{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:22px}.intelHeader small{color:#e44d2e;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.intelHeader h2{font-size:clamp(2rem,4vw,3.3rem);line-height:.95;letter-spacing:-.06em;margin:8px 0;color:#00338d}.intelHeader p{max-width:650px;color:#65758b}.intelGrid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.intelCard{background:white;border:1px solid #d9e2ef;border-radius:26px;padding:24px;box-shadow:0 18px 45px #00195016;margin-top:18px}.intelCard.dark{background:linear-gradient(135deg,#061b45,#00338d);color:white}.intelCard.gold{background:linear-gradient(135deg,#fff8d6,#ffffff);border-color:#ffcc00}.intelCard.dark p{color:#dbe7ff}.intelCard h3{margin:0 0 10px;color:#00338d}.intelCard.dark h3{color:white}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px}.metric{border-radius:18px;background:#f8fbff;border:1px solid #d9e2ef;padding:16px}.dark .metric{background:#ffffff14;border-color:#ffffff2e}.gold .metric{background:#fff;border-color:#fde68a}.metric b{display:block;font-size:1.5rem;color:#00338d}.dark .metric b{color:#ffcc00}.causeRow{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.causePill{border:1px solid #d9e2ef;background:#fff;border-radius:18px;padding:13px;font-weight:900}.causePill span{display:block;color:#65758b;font-weight:700;font-size:.86rem}.intelActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.intelBtn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;border-radius:999px;background:#ffcc00;color:#172033;font-weight:950;text-decoration:none;padding:0 16px}.intelBtn.blue{background:#0a48bd;color:white}.usefulLinks{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:18px}.usefulLink{display:block;border:1px solid #d9e2ef;background:#f8fbff;border-radius:20px;padding:18px;text-decoration:none;color:#172033}.usefulLink strong{display:block;color:#00338d;font-size:1.05rem}.usefulLink span{display:block;color:#65758b;font-size:.92rem;margin-top:3px}.officialUpdates{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:18px}.officialUpdate{border:1px solid #d9e2ef;border-radius:20px;padding:18px;background:#fff}.officialUpdate small{display:block;color:#e44d2e;font-weight:950;text-transform:uppercase;letter-spacing:.08em}.officialUpdate h4{margin:6px 0;color:#00338d;font-size:1.08rem}.officialUpdate p{margin:0}.officialUpdate a{display:inline-flex;margin-top:10px;color:#00338d;font-weight:950}@media(max-width:900px){.intelHeader,.intelGrid{display:block}.metrics,.causeRow,.usefulLinks,.officialUpdates{grid-template-columns:1fr}}
`;

function Metric({value,label}){return React.createElement('div',{className:'metric'},React.createElement('b',null,value),React.createElement('span',null,label));}

export default function HomeIntelligence(){
 const db=revistaDb,impact=db.global.impact,membership=db.global.membership,bulletin=membership.receivedBulletin,lcif=db.lcif.impact,causes=db.global.causes,usefulLinks=db.global.usefulLinks||[];
 const updates=[
  {date:'AL 2026/2027',title:'Com as raízes no serviço',text:'O Presidente Internacional Mark Lyon propõe quatro prioridades: serviço significativo, crescimento associativo, liderança que defende o próximo e fortalecimento da LCIF.',url:'https://www.lionsclubs.org/pt/discover-our-clubs/presidential-theme'},
  {date:'3 a 7 de julho de 2026',title:'108ª Convenção Internacional',text:'Hong Kong reuniu Leões e Leos para celebrar o serviço, reconhecer iniciativas, compartilhar atualizações da LCIF e renovar a mobilização da MISSÃO 1.5.',url:'https://lionscon.lionsclubs.org/pt-br/'},
  {date:'Último ano da MISSÃO 1.5',title:'Quanto mais crescemos, mais podemos servir',text:'A mobilização internacional continua incentivando novos associados, novos clubes e comunidades mais fortes por meio do serviço.',url:'https://www.lionsclubs.org/pt/resources-for-members/mission-to-grow'},
  {date:'Calendário 2026/2027',title:'Semanas de Serviços',text:'Visão em outubro de 2026, juventude em fevereiro de 2027 e meio ambiente entre maio e junho de 2027 orientam ações coletivas globais.',url:'https://www.lionsclubs.org/pt/member-resource-center/service/global-causes-initiatives/weeks-of-service'}
 ];
 return React.createElement(React.Fragment,null,
  React.createElement('style',{dangerouslySetInnerHTML:{__html:css}}),
  React.createElement('section',{className:'intelHome'},
   React.createElement('div',{className:'intelHeader'},React.createElement('div',null,React.createElement('small',null,'Site inteligente e revista mensal'),React.createElement('h2',null,'Dados que se transformam em serviço, memória e revista.')),React.createElement('p',null,'O portal conecta campanhas locais, memória institucional e conteúdos oficiais do movimento leonístico.')),
   React.createElement('div',{className:'intelGrid'},
    React.createElement('article',{className:'intelCard dark'},React.createElement('h3',null,'Impacto global Lions'),React.createElement('p',null,'Base oficial para contextualizar as campanhas locais.'),React.createElement('div',{className:'metrics'},React.createElement(Metric,{value:fmt.format(impact.peopleServed),label:'pessoas servidas'}),React.createElement(Metric,{value:fmt.format(impact.projectsCompleted),label:'projetos'}),React.createElement(Metric,{value:fmt.format(impact.lcifGrantsSince1968),label:'subsídios LCIF'})),React.createElement('div',{className:'intelActions'},React.createElement('a',{className:'intelBtn',href:'/revista'},'Abrir revista mensal'),React.createElement('a',{className:'intelBtn blue',href:'/campanhas'},'Campanhas locais'))),
    React.createElement('article',{className:'intelCard'},React.createElement('h3',null,'LCIF'),React.createElement('p',null,'Fundação global de apoio ao serviço humanitário.'),React.createElement('div',{className:'metrics'},React.createElement(Metric,{value:money.format(lcif.annualReport2024_2025.grantsTotalUSD),label:'subsídios 2024/2025'}),React.createElement(Metric,{value:fmt.format(lcif.annualReport2024_2025.grantsAwarded),label:'subsídios concedidos'}),React.createElement(Metric,{value:fmt.format(lcif.cataractSurgeries),label:'cirurgias de catarata'}))),
    React.createElement('article',{className:'intelCard gold'},React.createElement('h3',null,'MISSION 1.5: continuar crescendo'),React.createElement('div',{className:'metrics'},React.createElement(Metric,{value:fmt.format(bulletin.totalMembers),label:'associados'}),React.createElement(Metric,{value:fmt.format(bulletin.newClubsThisYear),label:'novos clubes'}),React.createElement(Metric,{value:fmt.format(bulletin.newMembersThisYear),label:'novos associados'}))),
    React.createElement('article',{className:'intelCard'},React.createElement('h3',null,'Atualizações oficiais do Lions'),React.createElement('p',null,'Destaques internacionais incorporados ao portal para orientar comunicação, planejamento e serviço.'),React.createElement('div',{className:'officialUpdates'},updates.map(item=>React.createElement('div',{className:'officialUpdate',key:item.title},React.createElement('small',null,item.date),React.createElement('h4',null,item.title),React.createElement('p',null,item.text),React.createElement('a',{href:item.url,target:'_blank',rel:'noreferrer'},'Consultar fonte oficial ↗'))))),
    React.createElement('article',{className:'intelCard'},React.createElement('h3',null,'Causas globais que orientam nossas campanhas'),React.createElement('div',{className:'causeRow'},causes.map(c=>React.createElement('div',{className:'causePill',key:c.name},c.name,React.createElement('span',null,c.peopleServed?fmt.format(c.peopleServed)+' pessoas servidas':'causa global Lions'))))),
    React.createElement('article',{className:'intelCard'},React.createElement('h3',null,'Links úteis para Lions e LCIF'),React.createElement('p',null,'Referências oficiais para consultas e recursos.'),React.createElement('div',{className:'usefulLinks'},usefulLinks.map(item=>React.createElement('a',{className:'usefulLink',href:item.url,target:'_blank',rel:'noreferrer',key:item.url},React.createElement('strong',null,item.title),React.createElement('span',null,item.description)))))
   )
  ));
}
