import React from 'react';

const script=`
(function(){
 const esc=v=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const toast=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}};
 let cached=[];
 async function loadAll(){try{const r=await fetch('/api/diretoria',{cache:'no-store'});const j=await r.json();if(j&&j.ok&&Array.isArray(j.data)){cached=j.data;return j.data;}}catch(e){}return cached;}
 function directors(data){return data.filter(x=>String(x.cargo||'').trim().toLowerCase()!=='associado');}
 function associates(data){return data.filter(x=>String(x.cargo||'').trim().toLowerCase()==='associado');}
 function renderDirectors(data){const grid=document.getElementById('directorGrid');if(!grid)return;grid.innerHTML=directors(data).map(d=>'<article><div class="avatar">'+esc((d.cargo||'L')[0])+'</div><h2>'+esc(d.cargo)+'</h2><p><b>'+esc(d.nome)+'</b></p><p>'+esc(d.funcao||'')+'</p></article>').join('');document.querySelectorAll('.notice').forEach(n=>{if((n.textContent||'').toLowerCase().includes('nomes pessoais'))n.remove();});}
 async function save(item){const r=await fetch('/api/diretoria',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erro ao salvar');return j.data;}
 async function remove(id){if(!id)throw new Error('Registro ainda não persistido no banco');const r=await fetch('/api/diretoria?id='+encodeURIComponent(id),{method:'DELETE'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erro ao excluir');}
 async function renderAssociadosAdmin(){const m=document.getElementById('adminMain');if(!m)return;const all=await loadAll();const data=associates(all);m.innerHTML='<h2>Associados <span class="dbBadge">seção separada</span></h2><form id="assocForm" class="form"><label>Nome do associado<input name="nome" required></label><button>Adicionar associado</button></form><table class="table adminEditableTable"><tbody>'+data.map((x,i)=>'<tr><td><b>'+esc(x.nome)+'</b></td><td><button data-aedit="'+i+'">Editar</button> <button data-adel="'+i+'">Excluir</button></td></tr>').join('')+'</tbody></table>';
  document.getElementById('assocForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await save({cargo:'Associado',nome:f.get('nome'),funcao:'Associado do Lions Clube de Juazeiro do Norte',periodo_al:'Quadro associativo atual',ordem:1000+data.length,ativo:true});toast('Associado adicionado');renderAssociadosAdmin();};
  m.querySelectorAll('[data-aedit]').forEach(b=>b.onclick=()=>{const x=data[+b.dataset.aedit];const nome=prompt('Editar nome do associado:',x.nome);if(!nome||nome===x.nome)return;save({...x,nome}).then(()=>{toast('Associado atualizado');renderAssociadosAdmin();}).catch(e=>toast(e.message));});
  m.querySelectorAll('[data-adel]').forEach(b=>b.onclick=()=>{const x=data[+b.dataset.adel];if(confirm('Excluir '+x.nome+'?'))remove(x.id).then(()=>{toast('Associado excluído');renderAssociadosAdmin();}).catch(e=>toast(e.message));});
 }
 function addAdminButton(){const aside=document.querySelector('#adminApp aside');if(!aside)return;let b=aside.querySelector('[data-tab="associados"]');if(!b){b=document.createElement('button');b.dataset.tab='associados';b.textContent='Associados';const users=aside.querySelector('[data-tab="users"]');if(users)aside.insertBefore(b,users);else aside.appendChild(b);}b.onclick=()=>renderAssociadosAdmin();}
 function addPublicLinks(){document.querySelectorAll('.mainMenu').forEach(menu=>{let a=menu.querySelector('a[href="/associados"]');if(!a){a=document.createElement('a');a.href='/associados';a.textContent='Associados';const dir=menu.querySelector('a[href="/diretoria"]');if(dir)dir.after(a);else menu.appendChild(a);}});document.querySelectorAll('.globalMobileGrid').forEach(menu=>{let a=menu.querySelector('a[href="/associados"]');if(!a){a=document.createElement('a');a.href='/associados';a.textContent='Associados';const camp=menu.querySelector('a[href="/campanhas"]');if(camp)camp.after(a);else menu.appendChild(a);}});}
 function ensureStyles(){let s=document.getElementById('institutional-revista-style');if(!s){s=document.createElement('style');s.id='institutional-revista-style';document.head.appendChild(s);}s.textContent='.institutionalPeopleGrid{display:grid;grid-template-columns:1fr 1fr;gap:5mm}.institutionalPerson{border:1px solid #d9e2ef;border-radius:5mm;padding:4mm;background:#fff}.institutionalPerson h3,.institutionalPerson p{margin:0 0 1.5mm}.associateNames{display:grid;grid-template-columns:1fr 1fr;gap:3mm 6mm}.associateName{border-bottom:1px solid #d9e2ef;padding:2.5mm 0;font-weight:800;color:#172033}@media(max-width:620px){.institutionalPeopleGrid,.associateNames{grid-template-columns:1fr}}';}
 function revistaPage(title,kicker,body,number,type){const s=document.createElement('section');s.className='magPage institutionalMagazinePage';s.dataset.page=number;s.dataset.peoplePage=type;s.innerHTML='<div class="kicker">'+kicker+'</div><h2>'+title+'</h2>'+body+'<div class="pageFooter"><span>Lions Clube Juazeiro do Norte · AL 2026/2027</span><span>'+number+'</span></div>';return s;}
 async function addRevistaPages(){if(!location.pathname.startsWith('/revista')||location.pathname.includes('al-2025-2026-003'))return;const stack=document.querySelector('.pageStack');if(!stack)return;ensureStyles();const data=await loadAll();const dirs=directors(data);const assoc=associates(data);if(!dirs.length&&!assoc.length)return;stack.querySelectorAll('.institutionalMagazinePage').forEach(x=>x.remove());const pDir=revistaPage('Diretoria do Lions Clube de Juazeiro do Norte','Governança e serviço','<div class="institutionalPeopleGrid">'+dirs.map(x=>'<div class="institutionalPerson"><h3>'+esc(x.cargo)+'</h3><p><b>'+esc(x.nome)+'</b></p><p>'+esc(x.funcao||'')+'</p></div>').join('')+'</div>','12','diretoria');const pAssoc=revistaPage('Associados do Lions Clube de Juazeiro do Norte','Quem faz o servir acontecer','<p>Quadro associativo atual, com todos os associados do clube:</p><div class="associateNames">'+assoc.map(x=>'<div class="associateName">'+esc(x.nome)+'</div>').join('')+'</div>','13','associados');const back=stack.querySelector('.backCover');if(back){stack.insertBefore(pDir,back);stack.insertBefore(pAssoc,back);}else{stack.appendChild(pDir);stack.appendChild(pAssoc);}}
 async function boot(){const data=await loadAll();renderDirectors(data);addAdminButton();addPublicLinks();addRevistaPages();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
 setTimeout(boot,500);setTimeout(boot,1500);setTimeout(boot,3500);setTimeout(boot,5000);
 const observer=new MutationObserver(()=>{addPublicLinks();addAdminButton();if(location.pathname.startsWith('/revista'))addRevistaPages();});
 observer.observe(document.documentElement,{childList:true,subtree:true});
})();
`;
export default function InstitutionalDataPatch(){return React.createElement('script',{dangerouslySetInnerHTML:{__html:script}});}
