import React from 'react';

const script=`
(function(){
 const esc=v=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const toast=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}};
 async function seed(){try{await fetch('/api/institucional-seed',{method:'POST'});}catch(e){}}
 async function loadAll(){try{const r=await fetch('/api/diretoria',{cache:'no-store'});const j=await r.json();return j&&j.ok&&Array.isArray(j.data)?j.data:[];}catch(e){return []}}
 function renderDirectors(data){const grid=document.getElementById('directorGrid');if(!grid)return;grid.innerHTML=data.filter(x=>x.cargo!=='Associado').map(d=>'<article><div class="avatar">'+esc((d.cargo||'L')[0])+'</div><h2>'+esc(d.cargo)+'</h2><p><b>'+esc(d.nome)+'</b></p><p>'+esc(d.funcao||'')+'</p></article>').join('');}
 async function save(item){const r=await fetch('/api/diretoria',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erro ao salvar');return j.data;}
 async function remove(id){const r=await fetch('/api/diretoria?id='+encodeURIComponent(id),{method:'DELETE'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Erro ao excluir');}
 async function renderAssociadosAdmin(){const m=document.getElementById('adminMain');if(!m)return;const all=await loadAll();const data=all.filter(x=>x.cargo==='Associado');m.innerHTML='<h2>Associados <span class="dbBadge">banco compartilhado</span></h2><form id="assocForm" class="form"><label>Nome do associado<input name="nome" required></label><button>Adicionar associado</button></form><table class="table adminEditableTable"><tbody>'+data.map((x,i)=>'<tr data-id="'+esc(x.id)+'"><td><b>'+esc(x.nome)+'</b></td><td><button data-aedit="'+i+'">Editar</button> <button data-adel="'+i+'">Excluir</button></td></tr>').join('')+'</tbody></table>';
  document.getElementById('assocForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await save({cargo:'Associado',nome:f.get('nome'),funcao:'Associado do Lions Clube de Juazeiro do Norte',periodo_al:'Quadro associativo atual',ordem:1000+data.length,ativo:true});toast('Associado adicionado ao banco');renderAssociadosAdmin();};
  m.querySelectorAll('[data-aedit]').forEach(b=>b.onclick=()=>{const x=data[+b.dataset.aedit];const nome=prompt('Editar nome do associado:',x.nome);if(!nome||nome===x.nome)return;save({...x,nome}).then(()=>{toast('Associado atualizado');renderAssociadosAdmin();});});
  m.querySelectorAll('[data-adel]').forEach(b=>b.onclick=()=>{const x=data[+b.dataset.adel];if(confirm('Excluir '+x.nome+'?'))remove(x.id).then(()=>{toast('Associado excluído');renderAssociadosAdmin();});});
 }
 function addAdminButton(){const aside=document.querySelector('#adminApp aside');if(!aside||aside.querySelector('[data-tab="associados"]'))return;const b=document.createElement('button');b.dataset.tab='associados';b.textContent='Associados';const users=aside.querySelector('[data-tab="users"]');if(users)aside.insertBefore(b,users);else aside.appendChild(b);b.onclick=()=>renderAssociadosAdmin();}
 function addPublicLink(){document.querySelectorAll('.mainMenu').forEach(menu=>{if(menu.querySelector('a[href="/associados"]'))return;const a=document.createElement('a');a.href='/associados';a.textContent='Associados';menu.appendChild(a);});document.querySelectorAll('.globalMobileGrid').forEach(menu=>{if(menu.querySelector('a[href="/associados"]'))return;const a=document.createElement('a');a.href='/associados';a.textContent='Associados';menu.appendChild(a);});}
 function revistaPage(title,kicker,body,number){const s=document.createElement('section');s.className='magPage';s.dataset.page=number;s.innerHTML='<div class="kicker">'+kicker+'</div><h2>'+title+'</h2>'+body+'<div class="pageFooter"><span>Lions Clube Juazeiro do Norte</span><span>'+number+'</span></div>';return s;}
 async function addRevistaPages(){if(!location.pathname.startsWith('/revista'))return;const stack=document.querySelector('.pageStack');if(!stack||stack.querySelector('[data-institutional-pages="1"]'))return;const issue3=location.pathname.includes('al-2025-2026-003');if(issue3)return;const data=await loadAll();const dirs=data.filter(x=>x.cargo!=='Associado');const assoc=data.filter(x=>x.cargo==='Associado');const pDir=revistaPage('Diretoria do Lions Clube de Juazeiro do Norte','Governança e serviço','<div class="grid2">'+dirs.map(x=>'<div class="card"><h3>'+esc(x.cargo)+'</h3><p><b>'+esc(x.nome)+'</b></p><p>'+esc(x.funcao||'')+'</p></div>').join('')+'</div>','12');pDir.dataset.institutionalPages='1';const pAssoc=revistaPage('Quadro associativo','Quem faz o servir acontecer','<p>Associados do Lions Clube de Juazeiro do Norte:</p><div class="grid2">'+assoc.map(x=>'<div class="card"><p><b>'+esc(x.nome)+'</b></p></div>').join('')+'</div>','13');pAssoc.dataset.institutionalPages='1';const back=stack.querySelector('.backCover');if(back){stack.insertBefore(pDir,back);stack.insertBefore(pAssoc,back);}else{stack.appendChild(pDir);stack.appendChild(pAssoc);}}
 async function boot(){await seed();const data=await loadAll();renderDirectors(data);addAdminButton();addPublicLink();addRevistaPages();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,1000);setTimeout(boot,2500);
})();
`;
export default function InstitutionalDataPatch(){return React.createElement('script',{dangerouslySetInnerHTML:{__html:script}});}
