import React from 'react';
import { MAIN_NAV, UTILITY_NAV, SITE_NAME, TAGLINE } from '../page';

export const metadata={title:'Quem somos | Lions Clube Juazeiro do Norte',description:'Conheça o Lions Clube Juazeiro do Norte, sua atuação, valores e o Hino à Bandeira do Lions.'};

const css=`
:root{--b:#00338d;--n:#061b45;--y:#ffcc00;--t:#172033;--m:#65758b;--l:#d9e2ef}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Segoe UI,Arial,sans-serif;color:var(--t)}a{text-decoration:none;color:inherit}.w{width:min(1180px,92vw);margin:auto}.siteHeader{position:sticky;top:0;z-index:10;background:#fffffff2;backdrop-filter:blur(14px);border-bottom:1px solid var(--l)}.utility{border-bottom:1px solid var(--l);font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}.utility .w,.brandRow,.mainNav{display:flex;align-items:center;justify-content:space-between;gap:22px}.utility .w{padding:9px 0}.utilityLinks,.mainMenu,.headerActions{display:flex;align-items:center;gap:20px;flex-wrap:wrap}.utilityLinks a,.mainMenu a{font-weight:900}.brandRow{padding:22px 0 18px}.brand{display:flex;align-items:center;gap:16px;font-weight:950;font-size:clamp(1.45rem,3vw,2.1rem)}.brand img{width:72px;height:72px;object-fit:contain}.brand small{display:block;color:var(--b);font-size:.9rem}.headerActions a{min-height:44px;border-radius:10px;padding:0 18px;display:flex;align-items:center;justify-content:center;font-weight:950}.join{background:#0a48bd;color:#fff}.donate{background:var(--y)}.mainNav{padding-bottom:18px}.mainMenu a{padding:8px 0;border-bottom:3px solid transparent}.mainMenu a.on{color:var(--b);border-color:var(--y)}.hero{background:linear-gradient(135deg,#eef5ff,#fff8d6);padding:72px 0}.ey{display:inline-flex;align-items:center;gap:8px;font-weight:900;color:#e44d2e;text-transform:uppercase;letter-spacing:.1em;font-size:.82rem}.hero h1{font-size:clamp(2.8rem,6vw,5.2rem);line-height:.92;letter-spacing:-.07em;color:var(--b);margin:14px 0}.hero p{font-size:1.15rem;color:var(--m);max-width:780px}.content{padding:54px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card,.hinoCard{border:1px solid var(--l);border-radius:24px;background:#fff;padding:24px;box-shadow:0 18px 45px #00195016}.card h2,.hinoCard h2{color:var(--b);margin-top:0}.card p,.hinoCard p{color:var(--m)}.hinoCard{margin-top:22px;background:linear-gradient(135deg,#061b45,#00338d);color:white;display:flex;justify-content:space-between;gap:24px;align-items:center}.hinoCard h2,.hinoCard p{color:white}.hinoCard a{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 18px;border-radius:999px;background:var(--y);color:#172033;font-weight:950;white-space:nowrap}.foot{background:var(--n);color:#dbe7ff;padding:42px 0;margin-top:50px}.foot h2{color:white}.foot p{color:#cbd7f2}@media(max-width:900px){.utility .w,.brandRow,.mainNav{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.hinoCard{display:block}.hinoCard a{margin-top:12px}.brand img{width:60px;height:60px}}
`;

function Header(){return React.createElement('header',{className:'siteHeader'},React.createElement('div',{className:'utility'},React.createElement('div',{className:'w'},React.createElement('div',{className:'utilityLinks'},UTILITY_NAV.map(x=>React.createElement('a',{href:x[0],key:x[0]},x[1]))))),React.createElement('div',{className:'brandRow w'},React.createElement('a',{className:'brand',href:'/'},React.createElement('img',{src:'/logo.png',alt:SITE_NAME}),React.createElement('span',null,SITE_NAME,React.createElement('small',null,TAGLINE))),React.createElement('div',{className:'headerActions'},React.createElement('a',{className:'join',href:'/voluntariado'},'Participar'),React.createElement('a',{className:'donate',href:'/campanhas'},'Apoiar'))),React.createElement('nav',{className:'mainNav w'},React.createElement('div',{className:'mainMenu'},MAIN_NAV.map(x=>React.createElement('a',{href:x[0],className:x[0]==='/quem-somos'?'on':'',key:x[0]},x[1])))));
}

export default function QuemSomosPage(){return React.createElement(React.Fragment,null,React.createElement('style',{dangerouslySetInnerHTML:{__html:css}}),React.createElement(Header),React.createElement('section',{className:'hero'},React.createElement('div',{className:'w'},React.createElement('span',{className:'ey'},'Serviço local'),React.createElement('h1',null,'Quem somos'),React.createElement('p',null,'O Lions Clube Juazeiro do Norte transforma necessidades da comunidade em campanhas, parcerias e ações concretas.'))),React.createElement('main',{className:'w content'},React.createElement('section',{className:'grid'},React.createElement('article',{className:'card'},React.createElement('h2',null,'Rede global'),React.createElement('p',null,'Integramos a tradição de Lions International: clubes formados por voluntários que servem suas comunidades.')),React.createElement('article',{className:'card'},React.createElement('h2',null,'Atuação no Cariri'),React.createElement('p',null,'Organizamos iniciativas em visão, fome, juventude, meio ambiente, diabetes, romarias e apoio humanitário.')),React.createElement('article',{className:'card'},React.createElement('h2',null,'Valores'),React.createElement('p',null,'Serviço, integridade, colaboração, diversidade, inovação e excelência orientam a atuação do clube.'))),React.createElement('section',{className:'hinoCard'},React.createElement('div',null,React.createElement('h2',null,'Hino do Lions'),React.createElement('p',null,'Acesse a página oficial do hino e acompanhe sua letra completa.')),React.createElement('a',{href:'/hino'},'Abrir página do Hino'))),React.createElement('section',{className:'card',style:{marginTop:22}},React.createElement('h2',null,'Propósito do portal'),React.createElement('p',null,'Centralizar campanhas, diretoria, voluntariado, transparência e comunicação oficial do Lions Clube Juazeiro do Norte.'))),React.createElement('footer',{className:'foot'},React.createElement('div',{className:'w'},React.createElement('h2',null,SITE_NAME),React.createElement('p',null,TAGLINE))));}
