import React from 'react';

export const metadata={title:'Associados | Lions Clube Juazeiro do Norte',description:'Quadro associativo do Lions Clube Juazeiro do Norte.'};

const css=`.assocPage{min-height:100vh;background:linear-gradient(180deg,#fff,#eef3f9);font-family:Inter,system-ui,Segoe UI,Arial,sans-serif;color:#172033}.assocHero{background:radial-gradient(circle at 82% 20%,#ffcc0055,transparent 28%),linear-gradient(135deg,#061b45,#00338d);color:#fff;padding:70px 0}.w{width:min(1180px,92vw);margin:auto}.assocHero small{color:#ffcc00;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.assocHero h1{font-size:clamp(2.6rem,6vw,5rem);line-height:.95;letter-spacing:-.06em;margin:12px 0}.assocHero p{max-width:760px;color:#dbe7ff;font-size:1.08rem}.assocMain{padding:38px 0 70px}.assocGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.assocCard{background:#fff;border:1px solid #d9e2ef;border-radius:22px;padding:20px;box-shadow:0 14px 35px #00195012}.assocCard span{display:grid;place-items:center;width:48px;height:48px;border-radius:50%;background:#fff8d6;color:#00338d;font-weight:950;margin-bottom:14px}.assocCard h2{font-size:1.12rem;color:#00338d;margin:0}.topLink{display:inline-flex;margin-bottom:22px;background:#ffcc00;color:#172033;border-radius:999px;padding:11px 17px;text-decoration:none;font-weight:950}.empty{background:#fff;border:1px dashed #b7c5d8;border-radius:22px;padding:30px;text-align:center;color:#65758b;font-weight:850}@media(max-width:820px){.assocGrid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.assocGrid{grid-template-columns:1fr}}`;

const script=`(function(){
 const esc=v=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 async function load(){const grid=document.getElementById('assocGrid');if(!grid)return;try{const r=await fetch('/api/diretoria',{cache:'no-store'});const j=await r.json();const data=j&&j.ok&&Array.isArray(j.data)?j.data.filter(x=>x.cargo==='Associado'):[];grid.innerHTML=data.length?data.map(x=>'<article class="assocCard"><span>L</span><h2>'+esc(x.nome)+'</h2></article>').join(''):'<div class="empty">Quadro associativo em atualização.</div>';}catch(e){grid.innerHTML='<div class="empty">Não foi possível carregar os associados agora.</div>';}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();`;

export default function AssociadosPage(){return <main className="assocPage"><style dangerouslySetInnerHTML={{__html:css}}/><section className="assocHero"><div className="w"><small>Quadro associativo</small><h1>Associados</h1><p>Conheça os associados que integram o Lions Clube de Juazeiro do Norte e fortalecem o serviço voluntário no Cariri.</p></div></section><section className="assocMain"><div className="w"><a className="topLink" href="/">Voltar ao início</a><div id="assocGrid" className="assocGrid"></div></div></section><script dangerouslySetInnerHTML={{__html:script}}/></main>}
